name = "CombinatorialMultigrid"
uuid = "44808c39-7784-4d8d-8dbc-3ef853c709a1"
authors = ["Bodhisatta Pramanik <bodhi91@iastate.edu>", "Yiannis Koutis <i.koutis@gmail.com>"]
version = "0.1.0"

[deps]
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LDLFactorizations = "0.8.1"
julia = "1.6"
